CREATE DATABASE IF NOT EXISTS C2526_M0486_RA2
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE C2526_M0486_RA2;
CREATE TABLE VisitaMedica (
IdVisita INT AUTO_INCREMENT PRIMARY KEY,
nomPacient VARCHAR(100) NOT NULL,
nomMetge VARCHAR(100) NOT NULL,
data DATE NOT NULL,
diagnostic TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
